### ISSUE TITLE
100 apologies

### ISSUE THREAD

**Issue by BigBoneDaddy** [BigBoneDaddy/my-repos#1]
@dom96 I am no troll. felixangell is harassing me because I pointed out bugs with his programming language. I do not know of the why he is offended but he is. Now he follow me to other projects I contribute to and he call me "jackass" like you saw. He deleted my comments because if he left them so public could see it would be obvious I am not trolling and that I found serious bugs with his softwares. As Nim user I do not want disruption to Nim project by felixangell. All I want is felixangell to leave me alone.

**Comment by dom96** [comment]
@BigBoneDaddy Could you email me on dom [at] picheta.me? I don't want to be discussing these things with you in public.

**Comment by BigBoneDaddy** [comment]
@dom96 I don't think there is more to discuss. I do not want to waste more your time with this petty matter. I just want you to know my intention is good and felixangell is clearly harassing me.

**Comment by dom96** [comment]
@BigBoneDaddy Don't worry about wasting my time. I just need some way to verify that you're not a troll, emailing me would be a good start.

**Comment by dom96** [comment]
@BigBoneDaddy well?
